# Generated by Django 5.2.12 on 2026-05-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilendiRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilendi_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('imported', 'Importé'), ('started', 'Commencé'), ('abandoned', 'Abandonné'), ('completed', 'Complété')], db_index=True, default='imported', max_length=16)),
                ('participant_code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('computed_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjusted_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trust_game_skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'exported_at'], name='bilendi_bil_status_057fbd_idx')],
            },
        ),
    ]
